local prefix = "#addon.gibsplat2."


localify.AddLanguage("en", "English")
localify.AddLanguage("zh-cn", "简体中文")


localify.Bind("en", prefix.."name", "GibSplat 2")
localify.Bind("en", prefix.."settings", "Settings")
localify.Bind("en", prefix.."menu_help", "Here you can change the GibSplat 2 settings.")

-- English
localify.Bind("en", prefix.."enabled", "Enabled")
localify.Bind("en", prefix.."keep_corpses", "Keep Corpses")
localify.Bind("en", prefix.."cleanup_gibs", "Cleanup Gibs")
localify.Bind("en", prefix.."reset_settings", "Reset Settings")
localify.Bind("en", prefix.."default_ragdolls", "Default Ragdolls")
localify.Bind("en", prefix.."player_ragdolls", "Player Ragdolls")
localify.Bind("en", prefix.."lua_effects", "Lua Effects")
localify.Bind("en", prefix.."effects", "Effects")
localify.Bind("en", prefix.."expensive_gibs", "Expensive Gibs")
localify.Bind("en", prefix.."custom_gibs", "Custom Gibs")
localify.Bind("en", prefix.."sv_gibs", "Serverside Gibs")
localify.Bind("en", prefix.."cl_gibs", "Clientside Gibs")
localify.Bind("en", prefix.."expensive_joints", "Expensive Joints")


localify.Bind("en", prefix.."max_decal_transfer", "Max Decal Transfer")
localify.Bind("en", prefix.."gib_limit", "Gib Limit")
localify.Bind("en", prefix.."particle_limit", "Particle Limit")
localify.Bind("en", prefix.."health_multiplier", "Health Multiplier")
localify.Bind("en", prefix.."explosion_gib_chance", "Explosion gib Chance")
localify.Bind("en", prefix.."explosion_chance", "Explosion Chance")
localify.Bind("en", prefix.."gib_spawnrate", "Gib Spawnrate")
localify.Bind("en", prefix.."gib_merge_chance", "Gib Merge Chance")
localify.Bind("en", prefix.."gib_lifetime", "Gib Lifetime")
localify.Bind("en", prefix.."particle_lifetime", "Particle Lifetime")
localify.Bind("en", prefix.."particle_linger_chance", "Particle Linger Chance")


localify.Bind("en", prefix.."desc_enabled", "Enable or disable the addon.")
localify.Bind("en", prefix.."desc_keep_corpses", "This needs to be on to be able to gib NPCs.")
localify.Bind("en", prefix.."desc_default_ragdolls", "Controls if all ragdolls should be gibbable.")
localify.Bind("en", prefix.."desc_player_ragdolls", "Controls if player ragdolls should be gibbable.")
localify.Bind("en", prefix.."desc_lua_effects", "Turn Lua based particle effects on or off.")
localify.Bind("en", prefix.."desc_effects", "Turn particle effects on or off.")
localify.Bind("en", prefix.."desc_expensive_gibs", "Controls if gibs should use a detailed physics mesh.")
localify.Bind("en", prefix.."desc_custom_gibs", "Controls whether to use custom model gibs or not (ribs etc)")
localify.Bind("en", prefix.."desc_sv_gibs", "Controls if gibs should be created server-side.")
localify.Bind("en", prefix.."desc_cl_gibs", "Controls if gibs should be created client-side")
localify.Bind("en", prefix.."desc_expensive_joints", "Controls whether joints can break from stress.")
localify.Bind("en", prefix.."desc_max_decal_transfer", "Maximum number of decals to transfer to a mesh part.")
localify.Bind("en", prefix.."desc_gib_limit", "Controls how many gibs can exist in the map.")
localify.Bind("en", prefix.."desc_particle_limit", "Controls how many particles can exist in the map.")
localify.Bind("en", prefix.."desc_health_multiplier", "The health of each body part will be multiplied by this.")
localify.Bind("en", prefix.."desc_explosion_gib_chance", "The chance of a ragdoll gibbing from explosion damage.")
localify.Bind("en", prefix.."desc_explosion_chance", "How much more likely the ragdoll is to gib from an explosion.")
localify.Bind("en", prefix.."desc_gib_spawnrate", "Controls how many gibs to spawn.")
localify.Bind("en", prefix.."desc_gib_merge_chance", "The chance of smaller gibs sticking together.")
localify.Bind("en", prefix.."desc_gib_lifetime", "Controls how long gibs stay before disappearing.")
localify.Bind("en", prefix.."desc_particle_lifetime", "Controls how long a particle stays.")
localify.Bind("en", prefix.."desc_particle_linger_chance", "The chance of a particle sticking to a surface.")

-- 简体中文/Chinese Simplified
localify.Bind("zh-cn", prefix.."name", "GibSplat2")
localify.Bind("zh-cn", prefix.."settings", "设置")
localify.Bind("zh-cn", prefix.."menu_help", "在此修改 GibSplat2 的设置")


localify.Bind("zh-cn", prefix.."enabled", "启用")
localify.Bind("zh-cn", prefix.."keep_corpses", "保留尸体")
localify.Bind("zh-cn", prefix.."cleanup_gibs", "清理断块")
localify.Bind("zh-cn", prefix.."reset_settings", "重置设置")
localify.Bind("zh-cn", prefix.."default_ragdolls", "默认布娃娃")
localify.Bind("zh-cn", prefix.."player_ragdolls", "玩家布娃娃")
localify.Bind("zh-cn", prefix.."lua_effects", "Lua 特效")
localify.Bind("zh-cn", prefix.."effects", "特效")
localify.Bind("zh-cn", prefix.."expensive_gibs", "启用高质量断块")
localify.Bind("zh-cn", prefix.."custom_gibs", "启用自定义断块")
localify.Bind("zh-cn", prefix.."sv_gibs", "启用服务端断块")
localify.Bind("zh-cn", prefix.."cl_gibs", "启用客户端断块")
localify.Bind("zh-cn", prefix.."expensive_joints", "高质量的关节")


localify.Bind("zh-cn", prefix.."max_decal_transfer", "最大贴图转移数量")
localify.Bind("zh-cn", prefix.."gib_limit", "断块限制数量")
localify.Bind("zh-cn", prefix.."particle_limit", "粒子限制数量")
localify.Bind("zh-cn", prefix.."health_multiplier", "生命值倍率")
localify.Bind("zh-cn", prefix.."explosion_gib_chance", "爆炸粉碎几率")
localify.Bind("zh-cn", prefix.."explosion_chance", "爆炸几率")
localify.Bind("zh-cn", prefix.."gib_spawnrate", "断块生成率")
localify.Bind("zh-cn", prefix.."gib_merge_chance", "断块合并几率")
localify.Bind("zh-cn", prefix.."gib_lifetime", "断块存在时间")
localify.Bind("zh-cn", prefix.."particle_lifetime", "粒子存在时间")
localify.Bind("zh-cn", prefix.."particle_linger_chance", "粒子附着几率")


localify.Bind("zh-cn", prefix.."desc_enabled", "启用或禁用此插件")
localify.Bind("zh-cn", prefix.."desc_keep_corpses", "需要开启才能启用 NPC 断肢效果")
localify.Bind("zh-cn", prefix.."desc_default_ragdolls", "控制所有布娃娃是否可粉碎")
localify.Bind("zh-cn", prefix.."desc_player_ragdolls", "控制玩家布娃娃是否可粉碎")
localify.Bind("zh-cn", prefix.."desc_lua_effects", "开启或关闭基于 Lua 的粒子效果")
localify.Bind("zh-cn", prefix.."desc_effects", "开启或关闭粒子效果")
localify.Bind("zh-cn", prefix.."desc_expensive_gibs", "控制断块是否使用高精度物理网格")
localify.Bind("zh-cn", prefix.."desc_custom_gibs", "控制是否使用自定义断块模型（如肋骨等）")
localify.Bind("zh-cn", prefix.."desc_sv_gibs", "控制断块是否在服务端生成")
localify.Bind("zh-cn", prefix.."desc_cl_gibs", "控制断块是否在客户端生成")
localify.Bind("zh-cn", prefix.."desc_expensive_joints", "控制关节是否会因压力而断裂")
localify.Bind("zh-cn", prefix.."desc_max_decal_transfer", "转移到网格部件的最大贴图数量")
localify.Bind("zh-cn", prefix.."desc_gib_limit", "控制地图中可存在的断块数量")
localify.Bind("zh-cn", prefix.."desc_particle_limit", "控制地图中可存在的粒子数量")
localify.Bind("zh-cn", prefix.."desc_health_multiplier", "身体各部位的生命值将乘以此值")
localify.Bind("zh-cn", prefix.."desc_explosion_gib_chance", "布娃娃因爆炸伤害而粉碎的几率")
localify.Bind("zh-cn", prefix.."desc_explosion_chance", "布娃娃因爆炸而粉碎的可能性的增加倍数")
localify.Bind("zh-cn", prefix.."desc_gib_spawnrate", "控制生成断块的数量")
localify.Bind("zh-cn", prefix.."desc_gib_merge_chance", "较小断块粘在一起的几率")
localify.Bind("zh-cn", prefix.."desc_gib_lifetime", "控制断块消失前的存在时间")
localify.Bind("zh-cn", prefix.."desc_particle_lifetime", "控制粒子存在的时间长度")
localify.Bind("zh-cn", prefix.."desc_particle_linger_chance", "粒子附着在表面的几率")